packages:
  - 'apps/*'
  - 'modules/*'
  - 'packages/*'
  - 'tooling/*'
allowBuilds:
  '@nestjs/core': true
  argon2: true
  '@prisma/engines': true
  lefthook: true
  prisma: true
  unrs-resolver: true
