name: cinema

volumes:
  postgres_data:
    name: cinema-postgres-data
  redis_data:
    name: cinema-redis-data
  ssl_certs:
    name: cinema-ssl-certs
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /etc/cinema/ssl

networks:
  cinema:
    name: cinema-net
    driver: bridge

include:
  # infra
  - ./infra/db.yml
  - ./infra/redis.yml
  # - ./infra/nginx.yml

  # services
  - ./services/migrator.yml
  - ./services/api.yml
  - ./services/worker.yml
  - ./services/scheduler.yml
  - ./services/integration.yml
  - ./services/web.yml
  - ./services/admin.yml
