import { HttpStatus } from '@nestjs/common';
import {
  AUTH_ERROR_CODE,
  COMMON_ERROR_CODE,
  IAM_ERROR_CODE,
  USER_ERROR_CODE,
  type AppErrorCode,
} from '@repo/contracts';

export const ERROR_CODE_HTTP_STATUS: Record<AppErrorCode, HttpStatus> = {
  [COMMON_ERROR_CODE.BAD_REQUEST]: HttpStatus.BAD_REQUEST,
  [COMMON_ERROR_CODE.VALIDATION]: HttpStatus.BAD_REQUEST,
  [COMMON_ERROR_CODE.UNAUTHORIZED]: HttpStatus.UNAUTHORIZED,
  [COMMON_ERROR_CODE.FORBIDDEN]: HttpStatus.FORBIDDEN,
  [COMMON_ERROR_CODE.NOT_FOUND]: HttpStatus.NOT_FOUND,
  [COMMON_ERROR_CODE.TIMEOUT]: HttpStatus.REQUEST_TIMEOUT,
  [COMMON_ERROR_CODE.CONFLICT]: HttpStatus.CONFLICT,
  [COMMON_ERROR_CODE.UNPROCESSABLE_ENTITY]: HttpStatus.UNPROCESSABLE_ENTITY,
  [COMMON_ERROR_CODE.TOO_MANY_REQUESTS]: HttpStatus.TOO_MANY_REQUESTS,
  [COMMON_ERROR_CODE.INTERNAL]: HttpStatus.INTERNAL_SERVER_ERROR,
  [COMMON_ERROR_CODE.NOT_IMPLEMENTED]: HttpStatus.NOT_IMPLEMENTED,
  [COMMON_ERROR_CODE.SERVICE_UNAVAILABLE]: HttpStatus.SERVICE_UNAVAILABLE,
  [COMMON_ERROR_CODE.GATEWAY_TIMEOUT]: HttpStatus.GATEWAY_TIMEOUT,

  [USER_ERROR_CODE.NOT_FOUND]: HttpStatus.NOT_FOUND,
  [USER_ERROR_CODE.INVALID]: HttpStatus.BAD_REQUEST,
  [USER_ERROR_CODE.EMAIL_ALREADY_EXISTS]: HttpStatus.CONFLICT,
  [USER_ERROR_CODE.USERNAME_ALREADY_EXISTS]: HttpStatus.CONFLICT,
  [USER_ERROR_CODE.INVALID_STATUS_TRANSITION]: HttpStatus.CONFLICT,

  [AUTH_ERROR_CODE.INVALID]: HttpStatus.BAD_REQUEST,
  [AUTH_ERROR_CODE.INVALID_CREDENTIALS]: HttpStatus.UNAUTHORIZED,
  [AUTH_ERROR_CODE.INVALID_TOKEN]: HttpStatus.UNAUTHORIZED,
  [AUTH_ERROR_CODE.EMAIL_NOT_VERIFIED]: HttpStatus.FORBIDDEN,
  [AUTH_ERROR_CODE.ACCOUNT_INACTIVE]: HttpStatus.FORBIDDEN,
  [AUTH_ERROR_CODE.SESSION_NOT_FOUND]: HttpStatus.UNAUTHORIZED,
  [AUTH_ERROR_CODE.SESSION_REVOKED]: HttpStatus.UNAUTHORIZED,
  [AUTH_ERROR_CODE.REFRESH_TOKEN_REUSED]: HttpStatus.UNAUTHORIZED,
  [AUTH_ERROR_CODE.CHALLENGE_INVALID]: HttpStatus.BAD_REQUEST,
  [AUTH_ERROR_CODE.CHALLENGE_EXPIRED]: HttpStatus.GONE,

  [IAM_ERROR_CODE.INVALID]: HttpStatus.BAD_REQUEST,
  [IAM_ERROR_CODE.ROLE_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [IAM_ERROR_CODE.PERMISSION_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [IAM_ERROR_CODE.ROLE_ALREADY_EXISTS]: HttpStatus.CONFLICT,
  [IAM_ERROR_CODE.PERMISSION_ALREADY_EXISTS]: HttpStatus.CONFLICT,
  [IAM_ERROR_CODE.SYSTEM_ROLE_IMMUTABLE]: HttpStatus.CONFLICT,
} as const;

export function getHttpStatusForErrorCode(code: AppErrorCode): HttpStatus {
  return ERROR_CODE_HTTP_STATUS[code] ?? HttpStatus.INTERNAL_SERVER_ERROR;
}
