import { HttpStatus } from '@nestjs/common';
import { COMMON_ERROR_CODE, USER_ERROR_CODE, type AppErrorCode } from '@repo/contracts';

export const ERROR_CODE_HTTP_STATUS: Record<AppErrorCode, HttpStatus> = {
  [COMMON_ERROR_CODE.BAD_REQUEST]: HttpStatus.BAD_REQUEST,
  [COMMON_ERROR_CODE.VALIDATION]: HttpStatus.BAD_REQUEST,
  [COMMON_ERROR_CODE.UNAUTHORIZED]: HttpStatus.UNAUTHORIZED,
  [COMMON_ERROR_CODE.FORBIDDEN]: HttpStatus.FORBIDDEN,
  [COMMON_ERROR_CODE.NOT_FOUND]: HttpStatus.NOT_FOUND,
  [COMMON_ERROR_CODE.TIMEOUT]: HttpStatus.REQUEST_TIMEOUT,
  [COMMON_ERROR_CODE.CONFLICT]: HttpStatus.CONFLICT,
  [COMMON_ERROR_CODE.UNPROCESSABLE_ENTITY]: HttpStatus.UNPROCESSABLE_ENTITY,
  [COMMON_ERROR_CODE.TOO_MANY_REQUESTS]: HttpStatus.TOO_MANY_REQUESTS,
  [COMMON_ERROR_CODE.INTERNAL]: HttpStatus.INTERNAL_SERVER_ERROR,
  [COMMON_ERROR_CODE.NOT_IMPLEMENTED]: HttpStatus.NOT_IMPLEMENTED,
  [COMMON_ERROR_CODE.SERVICE_UNAVAILABLE]: HttpStatus.SERVICE_UNAVAILABLE,
  [COMMON_ERROR_CODE.GATEWAY_TIMEOUT]: HttpStatus.GATEWAY_TIMEOUT,

  [USER_ERROR_CODE.NOT_FOUND]: HttpStatus.NOT_FOUND,
  [USER_ERROR_CODE.EMAIL_ALREADY_EXISTS]: HttpStatus.CONFLICT,
} as const;

export function getHttpStatusForErrorCode(code: AppErrorCode): HttpStatus {
  return ERROR_CODE_HTTP_STATUS[code] ?? HttpStatus.INTERNAL_SERVER_ERROR;
}
