export const AUTH_ERROR_CODE = {
  INVALID: 'AUTH.INVALID',
  INVALID_CREDENTIALS: 'AUTH.INVALID_CREDENTIALS',
  INVALID_TOKEN: 'AUTH.INVALID_TOKEN',
  EMAIL_NOT_VERIFIED: 'AUTH.EMAIL_NOT_VERIFIED',
  ACCOUNT_INACTIVE: 'AUTH.ACCOUNT_INACTIVE',
  SESSION_NOT_FOUND: 'AUTH.SESSION_NOT_FOUND',
  SESSION_REVOKED: 'AUTH.SESSION_REVOKED',
  REFRESH_TOKEN_REUSED: 'AUTH.REFRESH_TOKEN_REUSED',
  CHALLENGE_INVALID: 'AUTH.CHALLENGE_INVALID',
  CHALLENGE_EXPIRED: 'AUTH.CHALLENGE_EXPIRED',
} as const;

export type AuthErrorCode = (typeof AUTH_ERROR_CODE)[keyof typeof AUTH_ERROR_CODE];
