export const COMMON_ERROR_CODE = {
  BAD_REQUEST: 'COMMON.BAD_REQUEST',
  VALIDATION: 'COMMON.VALIDATION',
  UNAUTHORIZED: 'COMMON.UNAUTHORIZED',
  FORBIDDEN: 'COMMON.FORBIDDEN',
  NOT_FOUND: 'COMMON.NOT_FOUND',
  TIMEOUT: 'COMMON.TIMEOUT',
  CONFLICT: 'COMMON.CONFLICT',
  UNPROCESSABLE_ENTITY: 'COMMON.UNPROCESSABLE_ENTITY',
  TOO_MANY_REQUESTS: 'COMMON.TOO_MANY_REQUESTS',
  INTERNAL: 'COMMON.INTERNAL',
  NOT_IMPLEMENTED: 'COMMON.NOT_IMPLEMENTED',
  SERVICE_UNAVAILABLE: 'COMMON.SERVICE_UNAVAILABLE',
  GATEWAY_TIMEOUT: 'COMMON.GATEWAY_TIMEOUT',
} as const;

export type CommonErrorCode = (typeof COMMON_ERROR_CODE)[keyof typeof COMMON_ERROR_CODE];
