export const IAM_ERROR_CODE = {
  INVALID: 'IAM.INVALID',
  ROLE_NOT_FOUND: 'IAM.ROLE_NOT_FOUND',
  PERMISSION_NOT_FOUND: 'IAM.PERMISSION_NOT_FOUND',
  ROLE_ALREADY_EXISTS: 'IAM.ROLE_ALREADY_EXISTS',
  PERMISSION_ALREADY_EXISTS: 'IAM.PERMISSION_ALREADY_EXISTS',
  SYSTEM_ROLE_IMMUTABLE: 'IAM.SYSTEM_ROLE_IMMUTABLE',
} as const;

export type IamErrorCode = (typeof IAM_ERROR_CODE)[keyof typeof IAM_ERROR_CODE];
