export const USER_ERROR_CODE = {
  INVALID: 'USER.INVALID',
  NOT_FOUND: 'USER.NOT_FOUND',
  EMAIL_ALREADY_EXISTS: 'USER.EMAIL_ALREADY_EXISTS',
  USERNAME_ALREADY_EXISTS: 'USER.USERNAME_ALREADY_EXISTS',
  INVALID_STATUS_TRANSITION: 'USER.INVALID_STATUS_TRANSITION',
} as const;

export type UserErrorCode = (typeof USER_ERROR_CODE)[keyof typeof USER_ERROR_CODE];
