services:
  migrator:
    depends_on:
      db-provisioner:
        condition: service_completed_successfully
    networks:
      - cinema
    restart: 'no'
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
